name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          cd backend
          make deps

      - name: Run Backend Tests
        env:
          DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}
        run: |
          cd backend
          echo "Running backend tests..."
          make test-verbose
          echo "Backend tests completed!"

      - name: Build Backend
        run: |
          cd backend
          echo "Building backend application..."
          make build
          echo "Backend build completed!"

  deploy-to-railway:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: test-backend
    if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: |
          curl -LsSf https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "Deploying to Railway..."
          railway up --service Stock-insights

  # deploy-frontend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18'

  #     - name: Install dependencies
  #       run: |
  #         cd frontend
  #         npm install

  #     - name: Run Frontend Tests
  #       run: |
  #         cd frontend
  #         npm test

  #     - name: Build frontend
  #       run: |
  #         cd frontend
  #         npm run build

  #     - name: Deploy to Vercel
  #       uses: amondnet/vercel-action@v25
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
  #         working-directory: ./frontend 
